{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f5f90342",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score\n",
    "import xarray as xr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "70fbcbfe",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3460, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\nehag\\AppData\\Local\\Temp\\ipykernel_2188\\2448340106.py\", line 44, in <module>\n",
      "    plt.savefig(output_file, bbox_inches='tight')\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\pyplot.py\", line 996, in savefig\n",
      "    res = fig.savefig(*args, **kwargs)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 3328, in savefig\n",
      "    self.canvas.print_figure(fname, **kwargs)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2338, in print_figure\n",
      "    self.figure.draw(renderer)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 95, in draw_wrapper\n",
      "    result = draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 3125, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\cartopy\\mpl\\geoaxes.py\", line 535, in draw\n",
      "    return super().draw(renderer=renderer, **kwargs)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 3066, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\collections.py\", line 2078, in draw\n",
      "    coordinates = transform.transform(coordinates)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\transforms.py\", line 1490, in transform\n",
      "    res = self.transform_affine(self.transform_non_affine(values))\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\transforms.py\", line 2422, in transform_non_affine\n",
      "    return self._a.transform_non_affine(points)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\cartopy\\mpl\\geoaxes.py\", line 130, in transform_non_affine\n",
      "    return prj.transform_points(self.source_projection,\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\cartopy\\crs.py\", line 417, in transform_points\n",
      "    _safe_pj_transform(src_crs, self, x, y, z, trap=trap)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\cartopy\\crs.py\", line 65, in _safe_pj_transform\n",
      "    return transformer.transform(x, y, z, errcheck=trap)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\pyproj\\transformer.py\", line 833, in transform\n",
      "    iny, y_data_type = _copytobuffer(yy, inplace=inplace)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\pyproj\\utils.py\", line 129, in _copytobuffer\n",
      "    return xxx.astype(\"d\", order=\"C\", copy=not inplace), DataType.ARRAY\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 7.94 MiB for an array with shape (1040402,) and data type float64\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2057, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 818, in format_exception_as_a_whole\n",
      "    frames.append(self.format_record(r))\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 736, in format_record\n",
      "    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 155, in _format_traceback_lines\n",
      "    line = stack_line.render(pygmented=has_colors).rstrip('\\n') + '\\n'\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\stack_data\\core.py\", line 360, in render\n",
      "    start_line, lines = self.frame_info._pygmented_scope_lines\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\stack_data\\utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\stack_data\\core.py\", line 780, in _pygmented_scope_lines\n",
      "    lines = _pygmented_with_ranges(formatter, code, ranges)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\stack_data\\utils.py\", line 165, in _pygmented_with_ranges\n",
      "    return pygments.highlight(code, lexer, formatter).splitlines()\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\pygments\\__init__.py\", line 82, in highlight\n",
      "    return format(lex(code, lexer), formatter, outfile)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\pygments\\__init__.py\", line 61, in format\n",
      "    formatter.format(tokens, realoutfile)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\pygments\\formatters\\terminal256.py\", line 250, in format\n",
      "    return Formatter.format(self, tokensource, outfile)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\pygments\\formatter.py\", line 94, in format\n",
      "    return self.format_unencoded(tokensource, outfile)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\pygments\\formatters\\terminal256.py\", line 256, in format_unencoded\n",
      "    for ttype, value in tokensource:\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\stack_data\\utils.py\", line 158, in get_tokens\n",
      "    for ttype, value in super().get_tokens(text):\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\pygments\\lexer.py\", line 187, in streamer\n",
      "    for _, t, v in self.get_tokens_unprocessed(text):\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\pygments\\lexer.py\", line 629, in get_tokens_unprocessed\n",
      "    m = rexmatch(text, pos)\n",
      "MemoryError\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\formatters.py\", line 221, in catch_format_error\n",
      "    r = method(self, *args, **kwargs)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\formatters.py\", line 338, in __call__\n",
      "    return printer(obj)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\pylabtools.py\", line 152, in print_figure\n",
      "    fig.canvas.print_figure(bytes_io, **kw)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2338, in print_figure\n",
      "    self.figure.draw(renderer)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 95, in draw_wrapper\n",
      "    result = draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 3125, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\cartopy\\mpl\\geoaxes.py\", line 535, in draw\n",
      "    return super().draw(renderer=renderer, **kwargs)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 3066, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\collections.py\", line 2074, in draw\n",
      "    self.update_scalarmappable()\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\collections.py\", line 887, in update_scalarmappable\n",
      "    self._mapped_colors = self.to_rgba(self._A, self._alpha)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\cm.py\", line 493, in to_rgba\n",
      "    x = self.norm(x)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\colors.py\", line 1336, in __call__\n",
      "    result, is_scalar = self.process_value(value)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\matplotlib\\colors.py\", line 1312, in process_value\n",
      "    result = np.ma.array(data, mask=mask, dtype=dtype, copy=True)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\numpy\\ma\\core.py\", line 6610, in array\n",
      "    return MaskedArray(data, mask=mask, dtype=dtype, copy=copy,\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\numpy\\ma\\core.py\", line 2826, in __new__\n",
      "    _data = np.array(data, dtype=dtype, copy=copy,\n",
      "numpy.core._exceptions._ArrayMemoryError: Unable to allocate 3.96 MiB for an array with shape (721, 1440) and data type float32\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2057, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 818, in format_exception_as_a_whole\n",
      "    frames.append(self.format_record(r))\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 736, in format_record\n",
      "    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 155, in _format_traceback_lines\n",
      "    line = stack_line.render(pygmented=has_colors).rstrip('\\n') + '\\n'\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\stack_data\\core.py\", line 360, in render\n",
      "    start_line, lines = self.frame_info._pygmented_scope_lines\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\stack_data\\utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\stack_data\\core.py\", line 780, in _pygmented_scope_lines\n",
      "    lines = _pygmented_with_ranges(formatter, code, ranges)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\stack_data\\utils.py\", line 165, in _pygmented_with_ranges\n",
      "    return pygments.highlight(code, lexer, formatter).splitlines()\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\pygments\\__init__.py\", line 82, in highlight\n",
      "    return format(lex(code, lexer), formatter, outfile)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\pygments\\__init__.py\", line 61, in format\n",
      "    formatter.format(tokens, realoutfile)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\pygments\\formatters\\terminal256.py\", line 250, in format\n",
      "    return Formatter.format(self, tokensource, outfile)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\pygments\\formatter.py\", line 94, in format\n",
      "    return self.format_unencoded(tokensource, outfile)\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\pygments\\formatters\\terminal256.py\", line 256, in format_unencoded\n",
      "    for ttype, value in tokensource:\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\stack_data\\utils.py\", line 158, in get_tokens\n",
      "    for ttype, value in super().get_tokens(text):\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\pygments\\lexer.py\", line 187, in streamer\n",
      "    for _, t, v in self.get_tokens_unprocessed(text):\n",
      "  File \"C:\\Users\\nehag\\anaconda3\\lib\\site-packages\\pygments\\lexer.py\", line 629, in get_tokens_unprocessed\n",
      "    m = rexmatch(text, pos)\n",
      "MemoryError\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<Figure size 1600x800 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import os\n",
    "import xarray as xr\n",
    "import matplotlib.pyplot as plt\n",
    "import cartopy.crs as ccrs\n",
    "import numpy as np\n",
    "\n",
    "# Load the xarray dataset\n",
    "ds = xr.open_dataset('new.nc')\n",
    "\n",
    "# Create the Output folder if it doesn't exist\n",
    "output_folder = 'Output'\n",
    "os.makedirs(output_folder, exist_ok=True)\n",
    "\n",
    "# Split the dataset into three parts along the time dimension\n",
    "num_chunks = 9\n",
    "chunk_size = len(ds['time']) // num_chunks\n",
    "\n",
    "# Iterate through each chunk\n",
    "for chunk_index in range(num_chunks):\n",
    "    start_index = chunk_index * chunk_size\n",
    "    end_index = start_index + chunk_size\n",
    "\n",
    "    # Extract the chunk along the time dimension\n",
    "    ds_chunk = ds.isel(time=slice(start_index, end_index))\n",
    "\n",
    "    # Iterate through each time step in the current chunk\n",
    "    for time_index, time_value in enumerate(ds_chunk['time']):\n",
    "        # Create a figure with GeoAxes\n",
    "        fig = plt.figure(figsize=(16, 8))\n",
    "        projection = ccrs.PlateCarree()\n",
    "        ax = plt.subplot(projection=projection)\n",
    "        ax.coastlines()\n",
    "\n",
    "        # Iterate through each variable and plot on the GeoAxes\n",
    "        for var_name in ['z', 'u', 'r', 'pv', 'v', 'cc', 'q']:\n",
    "            ds_chunk[var_name].sel(time=time_value).plot(ax=ax, transform=ccrs.PlateCarree(), cmap='coolwarm', add_colorbar=False)\n",
    "\n",
    "        # Customize the title based on the target variable ('t' in this case)\n",
    "        target_values = ds_chunk['t'].sel(time=time_value).values\n",
    "        target_value = float(np.mean(target_values))  # Extract the mean value\n",
    "\n",
    "        # Save the figure with the target value as part of the filename\n",
    "        output_file = os.path.join(output_folder, f'earth_image_chunk{chunk_index}_time{time_index}_target_{target_value:.0f}.png')\n",
    "        plt.savefig(output_file, bbox_inches='tight')\n",
    "\n",
    "        # Close the figure to free up resources\n",
    "        plt.close()\n",
    "\n",
    "        # Display a message indicating that the figure was saved\n",
    "        print(f\"Figure saved to: {output_file}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "25f4ad6c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
